name: Test

on:
  pull_request: {}
  push:
    branches: master
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/jb-delafosse/thermodynamics/thermodynamics:latest
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: git --version
      - uses: actions/checkout@v2
        env:
            GIT_TRACE: 1
            GIT_CURL_VERBOSE: 1
      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev --site-packages

      - run: pipenv run isort . --check --diff
      - run: pipenv run black --check .
      - run: pipenv run flake8
      - run: pipenv run mypy
      - run: pipenv run pytest --cov --cov-fail-under=95
